apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test-ns
spec:
  type: NodePort
  selector:
    test_label: toto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
