apiVersion: gateway.shinemost.top/v1alpha1
kind: MyProxy
metadata:
  labels:
    app.kubernetes.io/name: myproxy
    app.kubernetes.io/instance: myproxy-sample
    app.kubernetes.io/part-of: test-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: test-operator
  name: myproxy-sample
spec:
  # TODO(user): Add fields here
